nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliateListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliate list model
    /// </summary>
    public partial record AffiliateListModel : BasePagedListModel<AffiliateModel>
    {
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliateModel.cs
using Nop.Web.Areas.Admin.Models.Common;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliate model
    /// </summary>
    public partial record AffiliateModel : BaseNopEntityModel
    {
        #region Ctor

        public AffiliateModel()
        {
            Address = new AddressModel();
            AffiliatedOrderSearchModel= new AffiliatedOrderSearchModel();
            AffiliatedCustomerSearchModel = new AffiliatedCustomerSearchModel();
        }

        #endregion

        #region Properties

        [NopResourceDisplayName("Admin.Affiliates.Fields.URL")]
        public string Url { get; set; }
        
        [NopResourceDisplayName("Admin.Affiliates.Fields.AdminComment")]
        public string AdminComment { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Fields.FriendlyUrlName")]
        public string FriendlyUrlName { get; set; }
        
        [NopResourceDisplayName("Admin.Affiliates.Fields.Active")]
        public bool Active { get; set; }

        public AddressModel Address { get; set; }

        public AffiliatedOrderSearchModel AffiliatedOrderSearchModel { get; set; }

        public AffiliatedCustomerSearchModel AffiliatedCustomerSearchModel { get; set; }

        #endregion
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliateSearchModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliate search model
    /// </summary>
    public partial record AffiliateSearchModel : BaseSearchModel
    {
        #region Properties

        [NopResourceDisplayName("Admin.Affiliates.List.SearchFirstName")]
        public string SearchFirstName { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.List.SearchLastName")]
        public string SearchLastName { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.List.SearchFriendlyUrlName")]
        public string SearchFriendlyUrlName { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.List.LoadOnlyWithOrders")]
        public bool LoadOnlyWithOrders { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.List.OrdersCreatedFromUtc")]
        [UIHint("DateNullable")]
        public DateTime? OrdersCreatedFromUtc { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.List.OrdersCreatedToUtc")]
        [UIHint("DateNullable")]
        public DateTime? OrdersCreatedToUtc { get; set; }

        #endregion
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliatedCustomerListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliated customer list model
    /// </summary>
    public partial record AffiliatedCustomerListModel : BasePagedListModel<AffiliatedCustomerModel>
    {
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliatedCustomerModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliated customer model
    /// </summary>
    public partial record AffiliatedCustomerModel : BaseNopEntityModel
    {
        #region Properties

        [NopResourceDisplayName("Admin.Affiliates.Customers.Name")]
        public string Name { get; set; }

        #endregion
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliatedCustomerSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliated customer search model
    /// </summary>
    public partial record AffiliatedCustomerSearchModel : BaseSearchModel
    {
        #region Properties

        public int AffliateId { get; set; }

        #endregion
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliatedOrderListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliated order list model
    /// </summary>
    public partial record AffiliatedOrderListModel : BasePagedListModel<AffiliatedOrderModel>
    {
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Models/Affiliates/AffiliatedOrderModel.cs
using System;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Web.Areas.Admin.Models.Affiliates
{
    /// <summary>
    /// Represents an affiliated order model
    /// </summary>
    public partial record AffiliatedOrderModel : BaseNopEntityModel
    {
        #region Properties

        public override int Id { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.CustomOrderNumber")]
        public string CustomOrderNumber { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.OrderStatus")]
        public string OrderStatus { get; set; }
        [NopResourceDisplayName("Admin.Affiliates.Orders.OrderStatus")]
        public int OrderStatusId { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.PaymentStatus")]
        public string PaymentStatus { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.ShippingStatus")]
        public string ShippingStatus { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.OrderTotal")]
        public string OrderTotal { get; set; }

        [NopResourceDisplayName("Admin.Affiliates.Orders.CreatedOn")]
        public DateTime CreatedOn { get; set; }

        #endregion
    }
}

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Controllers/AffiliateController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Affiliates;
using Nop.Core.Domain.Common;
using Nop.Services.Affiliates;
using Nop.Services.Common;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Affiliates;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class AffiliateController : BaseAdminController
    {
        #region Fields

        private readonly IAddressService _addressService;
        private readonly IAffiliateModelFactory _affiliateModelFactory;
        private readonly IAffiliateService _affiliateService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;

        #endregion

        #region Ctor

        public AffiliateController(IAddressService addressService,
            IAffiliateModelFactory affiliateModelFactory,
            IAffiliateService affiliateService,
            ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService)
        {
            _addressService = addressService;
            _affiliateModelFactory = affiliateModelFactory;
            _affiliateService = affiliateService;
            _customerActivityService = customerActivityService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            //prepare model
            var model =await _affiliateModelFactory.PrepareAffiliateSearchModelAsync(new AffiliateSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> List(AffiliateSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return await AccessDeniedDataTablesJson();

            //prepare model
            var model = await _affiliateModelFactory.PrepareAffiliateListModelAsync(searchModel);

            return Json(model);
        }

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            //prepare model
            var model = await _affiliateModelFactory.PrepareAffiliateModelAsync(new AffiliateModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual async Task<IActionResult> Create(AffiliateModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var address = model.Address.ToEntity<Address>();

                address.CreatedOnUtc = DateTime.UtcNow;

                //some validation
                if (address.CountryId == 0)
                    address.CountryId = null;
                if (address.StateProvinceId == 0)
                    address.StateProvinceId = null;

                await _addressService.InsertAddressAsync(address);

                var affiliate = model.ToEntity<Affiliate>();

                //validate friendly URL name
                var friendlyUrlName = await _affiliateService.ValidateFriendlyUrlNameAsync(affiliate, model.FriendlyUrlName);
                affiliate.FriendlyUrlName = friendlyUrlName;
                affiliate.AddressId = address.Id;

                await _affiliateService.InsertAffiliateAsync(affiliate);

                //activity log
                await _customerActivityService.InsertActivityAsync("AddNewAffiliate",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewAffiliate"), affiliate.Id), affiliate);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Affiliates.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = affiliate.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = await _affiliateModelFactory.PrepareAffiliateModelAsync(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual async Task<IActionResult> Edit(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            //try to get an affiliate with the specified id
            var affiliate = await _affiliateService.GetAffiliateByIdAsync(id);
            if (affiliate == null || affiliate.Deleted)
                return RedirectToAction("List");

            //prepare model
            var model = await _affiliateModelFactory.PrepareAffiliateModelAsync(null, affiliate);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual async Task<IActionResult> Edit(AffiliateModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            //try to get an affiliate with the specified id
            var affiliate = await _affiliateService.GetAffiliateByIdAsync(model.Id);
            if (affiliate == null || affiliate.Deleted)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                var address = await _addressService.GetAddressByIdAsync(affiliate.AddressId);
                address = model.Address.ToEntity(address);

                //some validation
                if (address.CountryId == 0)
                    address.CountryId = null;
                if (address.StateProvinceId == 0)
                    address.StateProvinceId = null;

                await _addressService.UpdateAddressAsync(address);

                affiliate = model.ToEntity(affiliate);

                //validate friendly URL name
                var friendlyUrlName = await _affiliateService.ValidateFriendlyUrlNameAsync(affiliate, model.FriendlyUrlName);
                affiliate.FriendlyUrlName = friendlyUrlName;
                affiliate.AddressId = address.Id;

                await _affiliateService.UpdateAffiliateAsync(affiliate);

                //activity log
                await _customerActivityService.InsertActivityAsync("EditAffiliate",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditAffiliate"), affiliate.Id), affiliate);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Affiliates.Updated"));

                if (!continueEditing)
                    return RedirectToAction("List");

                return RedirectToAction("Edit", new { id = affiliate.Id });
            }

            //prepare model
            model = await _affiliateModelFactory.PrepareAffiliateModelAsync(model, affiliate, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        //delete
        [HttpPost]
        public virtual async Task<IActionResult> Delete(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return AccessDeniedView();

            //try to get an affiliate with the specified id
            var affiliate = await _affiliateService.GetAffiliateByIdAsync(id);
            if (affiliate == null)
                return RedirectToAction("List");

            await _affiliateService.DeleteAffiliateAsync(affiliate);

            //activity log
            await _customerActivityService.InsertActivityAsync("DeleteAffiliate",
                string.Format(await _localizationService.GetResourceAsync("ActivityLog.DeleteAffiliate"), affiliate.Id), affiliate);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Affiliates.Deleted"));

            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual async Task<IActionResult> AffiliatedOrderListGrid(AffiliatedOrderSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageAffiliates))
                return await AccessDeniedDataTablesJson();

            //try to get an affiliate with the specified id
            var affiliate = await _affiliateService.GetAffiliateByIdAsync(searchModel.AffliateId)
                ?? throw new ArgumentException("No affiliate found with the specified id");

            //prepare model

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Views/Affiliate/Create.cshtml
@model AffiliateModel
@{
    //page title
    ViewBag.PageTitle = T("Admin.Affiliates.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Affiliates");
}

<form asp-controller="Affiliate" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Affiliates.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Affiliates.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.AffiliateDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Views/Affiliate/Edit.cshtml
@model AffiliateModel
@{
    //page title
    ViewBag.PageTitle = T("Admin.Affiliates.EditAffiliateDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Affiliates");
}
<form asp-controller="Affiliate" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Affiliates.EditAffiliateDetails") - @Model.Address.FirstName @Model.Address.LastName
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Affiliates.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="affiliate-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.AffiliateDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="affiliate-delete" />

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Views/Affiliate/List.cshtml
@model AffiliateSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Affiliates").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Affiliates");
}

@{
    const string hideSearchBlockAttributeName = "AffiliatePage.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.Affiliates")
    </h1>
    <div class="float-right">
        <a asp-action="Create" class="btn btn-primary">
            <i class="fas fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.AffiliateListButtons, additionalData = Model })
    </div>
</div>

<section class="content">
    <div class="container-fluid">
    <div class="form-horizontal">
        <div class="cards-group">
            <div class="card card-default card-search">
                <div class="card-body">
                    <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fas fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="far fa-angle-@(!hideSearchBlock ? "up" : "down")" aria-hidden="true"></i></div>
                    </div>

                    <div class="search-body @(hideSearchBlock ? "closed" : "")">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchFirstName" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="SearchFirstName" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchLastName" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="SearchLastName" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="SearchFriendlyUrlName" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="SearchFriendlyUrlName" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="LoadOnlyWithOrders" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="LoadOnlyWithOrders" />
                                    </div>
                                </div>
                                <nop-nested-setting asp-for="LoadOnlyWithOrders">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="OrdersCreatedFromUtc" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-editor asp-for="OrdersCreatedFromUtc" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <nop-label asp-for="OrdersCreatedToUtc" />
                                        </div>
                                        <div class="col-md-8">
                                            <nop-editor asp-for="OrdersCreatedToUtc" />
                                        </div>
                                    </div>
                                </nop-nested-setting>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center col-12">
                                <button type="button" id="search-affiliates" class="btn btn-primary btn-search">
                                    <i class="fas fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card card-default">
                <div class="card-body">
                    <p>
                        @T("Admin.Affiliates.Description")
                        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.Affiliates", Docs.Affiliates + Utm.OnAdmin)" asp-add-wrapper="false"/>
                    </p>

                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "affiliates-grid",
                        UrlRead = new DataUrl("List", "Affiliate", null),
                        SearchButtonId = "search-affiliates",
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(Model.SearchFirstName)),
                            new FilterParameter(nameof(Model.SearchLastName)),
                            new FilterParameter(nameof(Model.SearchFriendlyUrlName)),
                            new FilterParameter(nameof(Model.LoadOnlyWithOrders), typeof(bool)),
                            new FilterParameter(nameof(Model.OrdersCreatedFromUtc)),
                            new FilterParameter(nameof(Model.OrdersCreatedToUtc))
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty($"{nameof(AffiliateModel.Address)}.{nameof(AddressModel.FirstName)}")
                            {
                                Title = T("Admin.Address.Fields.FirstName").Text,
                                Width = "200"
                            },
                            new ColumnProperty($"{nameof(AffiliateModel.Address)}.{nameof(AddressModel.LastName)}")
                            {
                                Title = T("Admin.Address.Fields.LastName").Text,
                                Width = "200"
                            },
                            new ColumnProperty(nameof(AffiliateModel.Active))
                            {
                                Title = T("Admin.Affiliates.Fields.Active").Text,
                                Width = "100",
                                ClassName = NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(AffiliateModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </div>
</div>
</section>

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Views/Affiliate/_CreateOrUpdate.Customers.cshtml
@model AffiliateModel
<div class="card-body">
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "customers-grid",
        UrlRead = new DataUrl("AffiliatedCustomerList", "Affiliate", new RouteValueDictionary { [nameof(Model.AffiliatedCustomerSearchModel.AffliateId)] = Model.AffiliatedCustomerSearchModel.AffliateId }),
        Length = Model.AffiliatedCustomerSearchModel.PageSize,
        LengthMenu = Model.AffiliatedCustomerSearchModel.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(AffiliatedCustomerModel.Id))
            {
                Title = "ID",
                Width = "50"
            },
            new ColumnProperty(nameof(AffiliatedCustomerModel.Name))
            {
                Title = T("Admin.Affiliates.Customers.Name").Text,
                Width = "200"
            },
            new ColumnProperty(nameof(AffiliatedCustomerModel.Id))
            {
                Title = T("Admin.Common.View").Text,
                Width = "150",
                ClassName = NopColumnClassDefaults.Button,
                Render = new RenderButtonView(new DataUrl("~/Admin/Customer/Edit/", nameof(AffiliatedCustomerModel.Id)))
            }
        }
    })
</div>

nopCommerce-release-4.50.3/src/Presentation/Nop.Web/Areas/Admin/Views/Affiliate/_CreateOrUpdate.Info.cshtml
@model AffiliateModel

<div class="card-body">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                @if (Model.Id > 0)
                {
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="Url" />
                        </div>
                        <div class="col-md-9">
                            <div class="form-text-row">@Model.Url</div>
                        </div>
                    </div>
                }
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="Active" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Active" />
                        <span asp-validation-for="Active"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-default">
            <div class="card-body">
                <nop-editor asp-for="Address" asp-template="Address" />
            </div>
        </div>
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AdminComment" />
                    </div>
                    <div class="col-md-9">
                        <nop-textarea asp-for="AdminComment"></nop-textarea>
                        <span asp-validation-for="AdminComment"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="FriendlyUrlName" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="FriendlyUrlName" />
                        <span asp-validation-for="FriendlyUrlName"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>